version: "3"
services:
  node:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://mongo_container:27017/mydb
      - NODE_ENV=deployment
    entrypoint: "node index.js"
  mongodb:
    image: mongo:7.0
    container_name: mongo_container
    ports:
      - "27017:27017"

